//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mAuthentication
    {
        public int x_ { get; set; }
        public Nullable<int> xUser_ { get; set; }
        public Nullable<int> xGroup_ { get; set; }
        public Nullable<bool> xInsert { get; set; }
        public Nullable<bool> xUpdate { get; set; }
        public Nullable<bool> xDelete { get; set; }
        public Nullable<int> xObject_ { get; set; }
    
        public virtual mGroup mGroup { get; set; }
        public virtual mObject mObject { get; set; }
        public virtual mUser mUser { get; set; }
    }
}
