//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mClientReferral
    {
        public mClientReferral()
        {
            this.mClientReferralFollowUps = new HashSet<mClientReferralFollowUp>();
        }
    
        public int x_ { get; set; }
        public string xTime { get; set; }
        public string xDate { get; set; }
        public string xClientReferral { get; set; }
        public string xTel { get; set; }
        public string xRequestedGoods { get; set; }
        public string xAmount { get; set; }
        public string xAddress { get; set; }
        public string xAction { get; set; }
        public Nullable<int> xGenReferTo_ { get; set; }
        public string xReferName { get; set; }
        public Nullable<bool> xReferConfirm { get; set; }
        public Nullable<int> xReferConfirmSupplier_ { get; set; }
        public string xReferConfirmDate { get; set; }
        public Nullable<long> xContractPrice { get; set; }
        public Nullable<long> xRecommenderCommission { get; set; }
        public Nullable<bool> xReferFinanceConfirm { get; set; }
        public Nullable<int> xSupplier_ { get; set; }
        public Nullable<bool> xSendWellComeMessage { get; set; }
        public Nullable<int> xGenResultOfReferral_ { get; set; }
        public string xComment { get; set; }
    
        public virtual ICollection<mClientReferralFollowUp> mClientReferralFollowUps { get; set; }
    }
}
