//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mClientReferralSurvey
    {
        public int x_ { get; set; }
        public Nullable<int> xClientReferral_ { get; set; }
        public Nullable<int> xGenSurveyForWho_ { get; set; }
        public Nullable<int> xAnswerNumber { get; set; }
        public string xQuestion { get; set; }
        public string xAnswerContext { get; set; }
    }
}
