//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mCompany
    {
        public int x_ { get; set; }
        public string xCompanyName { get; set; }
        public string xBusinessNumber { get; set; }
        public string xRegistrationNumber { get; set; }
        public string xNationalCode { get; set; }
        public string xFieldActivity { get; set; }
        public string xTel { get; set; }
        public string xFax { get; set; }
        public string xEmail { get; set; }
        public string xZipCode { get; set; }
        public string xAddress { get; set; }
        public string xWebsite { get; set; }
        public string xSupplyManager { get; set; }
        public string xSupplyManagerTel { get; set; }
        public string xDirectorFactor { get; set; }
        public string xDirectorFactorTel { get; set; }
        public Nullable<int> xGrade { get; set; }
        public string xGradeDate { get; set; }
        public string xSerial { get; set; }
        public string xEvaluationPerson { get; set; }
        public Nullable<int> xSupplier_ { get; set; }
        public string xComment { get; set; }
        public Nullable<bool> xActive { get; set; }
    }
}
