//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mContractor
    {
        public mContractor()
        {
            this.mContractorsEvaluations = new HashSet<mContractorsEvaluation>();
        }
    
        public int x_ { get; set; }
        public string xName { get; set; }
        public string xFamily { get; set; }
        public string xFatherName { get; set; }
        public Nullable<int> xGenJob_ { get; set; }
        public string xNationalCode { get; set; }
        public string xMobile { get; set; }
        public string xTel { get; set; }
        public string xZone { get; set; }
        public string xAddress { get; set; }
        public Nullable<int> xSupplier_ { get; set; }
    
        public virtual ICollection<mContractorsEvaluation> mContractorsEvaluations { get; set; }
    }
}
