//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mContractorsEvaluation
    {
        public int x_ { get; set; }
        public Nullable<int> xContractors_ { get; set; }
        public Nullable<int> xGenEvaluationName_ { get; set; }
        public Nullable<int> xScore { get; set; }
        public Nullable<int> xSupplier_ { get; set; }
    
        public virtual mContractor mContractor { get; set; }
        public virtual mGenGroup mGenGroup { get; set; }
    }
}
