//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mGoodsAndSupplierInfo
    {
        public int x_ { get; set; }
        public Nullable<int> xGoods_ { get; set; }
        public Nullable<int> xCompany_ { get; set; }
        public string xBrand { get; set; }
        public string xOrderSupplyPeriod { get; set; }
        public Nullable<int> xDeliveryDayNumber { get; set; }
        public string xSettlementType { get; set; }
        public string xContractType { get; set; }
        public string xLastSupplierGrade { get; set; }
        public string xMinimumInventoryRequired { get; set; }
        public string xSalesExpertName { get; set; }
        public string xSalesExpertNameAlternatives { get; set; }
        public Nullable<int> xSupplier_ { get; set; }
    }
}
