//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mGood
    {
        public mGood()
        {
            this.mStoreDetials = new HashSet<mStoreDetial>();
        }
    
        public int x_ { get; set; }
        public string xName { get; set; }
        public string xCode { get; set; }
        public Nullable<int> xGenGroup_ { get; set; }
        public Nullable<int> xGenUnit_ { get; set; }
        public Nullable<int> xSupplier_ { get; set; }
    
        public virtual ICollection<mStoreDetial> mStoreDetials { get; set; }
    }
}
