//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mGroup
    {
        public mGroup()
        {
            this.mAuthentications = new HashSet<mAuthentication>();
            this.mUsers = new HashSet<mUser>();
        }
    
        public int x_ { get; set; }
        public string xGroupName { get; set; }
    
        public virtual ICollection<mAuthentication> mAuthentications { get; set; }
        public virtual ICollection<mUser> mUsers { get; set; }
    }
}
