//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mMarketerInformationFollowUp
    {
        public int x_ { get; set; }
        public string xDate { get; set; }
        public string xTime { get; set; }
        public Nullable<int> xGenFollowUp_ { get; set; }
        public string xComment { get; set; }
        public Nullable<int> xSupplier_ { get; set; }
        public Nullable<int> xMarketerInformation_ { get; set; }
    
        public virtual mMarketerInformation mMarketerInformation { get; set; }
    }
}
