//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mMessage
    {
        public int x_ { get; set; }
        public string xDate { get; set; }
        public int xUser_ { get; set; }
        public string xSubject { get; set; }
        public string xContext { get; set; }
        public string xDateExpire { get; set; }
        public Nullable<int> xSendTo_ { get; set; }
        public string xDateRead { get; set; }
        public Nullable<bool> xDo { get; set; }
        public string xType { get; set; }
        public string xLetterId { get; set; }
        public string xReplyFrom { get; set; }
        public string xCurrentTime { get; set; }
        public string xMessageFrom { get; set; }
        public Nullable<bool> xElan { get; set; }
        public string xRdTlg { get; set; }
        public Nullable<int> xFileId_ { get; set; }
    }
}
