//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mObjectGroup
    {
        public mObjectGroup()
        {
            this.mObjects = new HashSet<mObject>();
        }
    
        public int x_ { get; set; }
        public string xName { get; set; }
    
        public virtual ICollection<mObject> mObjects { get; set; }
    }
}
