//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mObjectTree
    {
        public int x_ { get; set; }
        public Nullable<int> xObject_ { get; set; }
        public Nullable<int> xParent_ { get; set; }
        public string xName { get; set; }
        public Nullable<int> xOrder { get; set; }
    }
}
