//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mPersonInfo
    {
        public mPersonInfo()
        {
            this.mUsers = new HashSet<mUser>();
        }
    
        public int x_ { get; set; }
        public Nullable<bool> xActive { get; set; }
        public string xPerID { get; set; }
        public string xName { get; set; }
        public string xFamily { get; set; }
        public Nullable<int> xSection_ { get; set; }
        public string xPost { get; set; }
        public string xMob { get; set; }
        public string xBirthDay { get; set; }
        public string xDateEmployeement { get; set; }
        public Nullable<int> xEducation_ { get; set; }
        public string xFatherName { get; set; }
        public Nullable<int> xSex_ { get; set; }
        public string xNationalCode { get; set; }
        public string xAddress { get; set; }
        public string xTel { get; set; }
        public string xIdentity { get; set; }
        public string xEmail { get; set; }
    
        public virtual mGenGroup mGenGroup { get; set; }
        public virtual mGenGroup mGenGroup1 { get; set; }
        public virtual mGenGroup mGenGroup2 { get; set; }
        public virtual ICollection<mUser> mUsers { get; set; }
    }
}
