//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mQuestion
    {
        public mQuestion()
        {
            this.mQuestionItems = new HashSet<mQuestionItem>();
        }
    
        public int x_ { get; set; }
        public string xQuestion { get; set; }
        public Nullable<int> xGenType_ { get; set; }
        public Nullable<int> xGenGroupLevel1_ { get; set; }
        public Nullable<int> xGenGroupLevel2_ { get; set; }
        public Nullable<bool> xPublic { get; set; }
        public Nullable<int> xOrder { get; set; }
        public Nullable<bool> xActive { get; set; }
    
        public virtual mGenGroup mGenGroup { get; set; }
        public virtual mGenGroup mGenGroup1 { get; set; }
        public virtual ICollection<mQuestionItem> mQuestionItems { get; set; }
    }
}
