//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mRebuilding
    {
        public int x_ { get; set; }
        public string xDate { get; set; }
        public Nullable<int> xCustomer_ { get; set; }
        public Nullable<int> xGenUsageType_ { get; set; }
        public Nullable<int> xBuldingStatus_ { get; set; }
        public Nullable<int> xArea { get; set; }
        public string xZone { get; set; }
        public string xAddress { get; set; }
        public Nullable<int> xGenPosition_ { get; set; }
        public Nullable<int> xlength { get; set; }
        public Nullable<int> xWidth { get; set; }
        public Nullable<int> xGenContractType_ { get; set; }
        public Nullable<bool> xLicenseRebuilding { get; set; }
        public string xLicenseRebuildingComment { get; set; }
        public Nullable<bool> xProductionLicense { get; set; }
        public string xProductionLicenseComment { get; set; }
        public Nullable<int> xBuildingUnitsNumber { get; set; }
        public Nullable<int> xFloorsNumber { get; set; }
        public Nullable<int> xBuildingUnitsNumberRequest { get; set; }
        public Nullable<int> xUnitID { get; set; }
        public Nullable<int> xUnitArea { get; set; }
        public Nullable<int> xAreaRebuilding { get; set; }
        public string xBuildingYear { get; set; }
        public Nullable<int> xBedroomsNumber { get; set; }
        public Nullable<int> xBedroomsNumber_Ch { get; set; }
        public Nullable<bool> xBedroomsNumber_Crr { get; set; }
        public Nullable<bool> xBedroomsNumber_CkM { get; set; }
        public string xBedroomsNumber_Remark { get; set; }
        public Nullable<int> xBathroomNumber { get; set; }
        public Nullable<int> xBathroomNumber_Ch { get; set; }
        public Nullable<bool> xBathroomNumber_Crr { get; set; }
        public Nullable<bool> xBathroomNumber_CkM { get; set; }
        public string xBathroomNumber_Remark { get; set; }
        public Nullable<int> xToiletNumber { get; set; }
        public Nullable<int> xToiletNumber_Ch { get; set; }
        public Nullable<bool> xToiletNumber_Crr { get; set; }
        public Nullable<bool> xToiletNumber_CkM { get; set; }
        public string xToiletNumber_Remark { get; set; }
        public Nullable<int> xGenRoof_ { get; set; }
        public Nullable<int> xGenRoof_Ch_ { get; set; }
        public Nullable<bool> xGenRoof_Crr { get; set; }
        public Nullable<bool> xGenRoof_CkM { get; set; }
        public string xGenRoof_Remark { get; set; }
        public Nullable<int> xGenBuildingSkeleton_ { get; set; }
        public Nullable<int> xGenBuildingSkeleton_Ch_ { get; set; }
        public Nullable<bool> xGenBuildingSkeleton_Crr { get; set; }
        public Nullable<bool> xGenBuildingSkeleton_CkM { get; set; }
        public string xGenBuildingSkeleton_Remark { get; set; }
        public Nullable<int> xGenFoundation_ { get; set; }
        public Nullable<int> xGenFoundation_Ch_ { get; set; }
        public Nullable<bool> xGenFoundation_Crr { get; set; }
        public Nullable<bool> xGenFoundation_CkM { get; set; }
        public string xGenFoundation_Remark { get; set; }
        public Nullable<int> xGenWall_ { get; set; }
        public Nullable<int> xGenWall_Ch_ { get; set; }
        public Nullable<bool> xGenWall_Crr { get; set; }
        public Nullable<bool> xGenWall_CkM { get; set; }
        public string xGenWall_Remark { get; set; }
        public Nullable<int> xGenWaterPiping_ { get; set; }
        public Nullable<int> xGenWaterPiping_Ch_ { get; set; }
        public Nullable<bool> xGenWaterPiping_Crr { get; set; }
        public Nullable<bool> xGenWaterPiping_CkM { get; set; }
        public string xGenWaterPiping_Remark { get; set; }
        public Nullable<int> xGenGasPiping_ { get; set; }
        public Nullable<int> xGenGasPiping_Ch_ { get; set; }
        public Nullable<bool> xGenGasPiping_Crr { get; set; }
        public Nullable<bool> xGenGasPiping_CkM { get; set; }
        public string xGenGasPiping_Remark { get; set; }
        public Nullable<int> xGenCoolingSystem_ { get; set; }
        public Nullable<int> xGenCoolingSystem_Ch_ { get; set; }
        public Nullable<bool> xGenCoolingSystem_Crr { get; set; }
        public Nullable<bool> xGenCoolingSystem_CkM { get; set; }
        public string xGenCoolingSystem_Remark { get; set; }
        public Nullable<int> xGenHeatingSystem_ { get; set; }
        public Nullable<int> xGenHeatingSystem_Ch_ { get; set; }
        public Nullable<bool> xGenHeatingSystem_Crr { get; set; }
        public Nullable<bool> xGenHeatingSystem_CkM { get; set; }
        public string xGenHeatingSystem_Remark { get; set; }
        public Nullable<int> xGenFlooring_ { get; set; }
        public Nullable<int> xGenFlooring_Ch_ { get; set; }
        public Nullable<bool> xGenFlooring_Crr { get; set; }
        public Nullable<bool> xGenFlooring_CkM { get; set; }
        public string xGenFlooring_Remark { get; set; }
        public Nullable<int> xGenKitchenWall_ { get; set; }
        public Nullable<int> xGenKitchenWall_Ch_ { get; set; }
        public Nullable<bool> xGenKitchenWall_Crr { get; set; }
        public Nullable<bool> xGenKitchenWall_CkM { get; set; }
        public string xGenKitchenWall_Remark { get; set; }
        public Nullable<int> xGenKitchenFloor_ { get; set; }
        public Nullable<int> xGenKitchenFloor_Ch_ { get; set; }
        public Nullable<bool> xGenKitchenFloor_Crr { get; set; }
        public Nullable<bool> xGenKitchenFloor_CkM { get; set; }
        public string xGenKitchenFloor_Remark { get; set; }
        public Nullable<int> xGenKitchenCupboards_ { get; set; }
        public Nullable<int> xGenKitchenCupboards_Ch_ { get; set; }
        public Nullable<bool> xGenKitchenCupboards_Crr { get; set; }
        public Nullable<bool> xGenKitchenCupboards_CkM { get; set; }
        public string xGenKitchenCupboards_Remark { get; set; }
        public Nullable<int> xGenBathroomPiping_ { get; set; }
        public Nullable<int> xGenBathroomPiping_Ch_ { get; set; }
        public Nullable<bool> xGenBathroomPiping_Crr { get; set; }
        public Nullable<bool> xGenBathroomPiping_CkM { get; set; }
        public string xGenBathroomPiping_Remark { get; set; }
        public Nullable<bool> xBathtub { get; set; }
        public Nullable<bool> xBathtub_Ch { get; set; }
        public Nullable<bool> xBathtub_Crr { get; set; }
        public Nullable<bool> xBathtub_CkM { get; set; }
        public string xBathtub_Remark { get; set; }
        public Nullable<bool> xBathTile { get; set; }
        public Nullable<bool> xBathTile_Ch { get; set; }
        public Nullable<bool> xBathTile_Crr { get; set; }
        public Nullable<bool> xBathTile_CkM { get; set; }
        public string xBathTile_Remark { get; set; }
        public Nullable<int> xGenAdaptationMap_ { get; set; }
        public Nullable<int> xGenPrepareCurrentSituationMaps_ { get; set; }
        public Nullable<int> xGenAmountDestruction_ { get; set; }
        public Nullable<int> xWeightDestruction { get; set; }
        public Nullable<int> xGenTransportDestructionMetod_ { get; set; }
        public Nullable<int> xGenAccessDestructionMetod_ { get; set; }
        public Nullable<int> xNeighborUnitCount { get; set; }
        public Nullable<int> xNeighborsLivingNumber { get; set; }
        public Nullable<int> xRiskNeighborsComplaints { get; set; }
        public Nullable<int> xRiskMunicipalityPrevent { get; set; }
        public Nullable<int> xRiskForcedDestruction { get; set; }
        public Nullable<int> xRiskDamageBuilding { get; set; }
        public Nullable<int> xDestructionDurationDay { get; set; }
        public Nullable<int> xDestructionRebuildingDay { get; set; }
        public Nullable<int> xGenReasonsRebuilding_ { get; set; }
        public Nullable<int> xSupplier_ { get; set; }
    }
}
