//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mRenovationUnit
    {
        public int x_ { get; set; }
        public Nullable<int> xRenovation_ { get; set; }
        public Nullable<int> xUnitNumber { get; set; }
        public Nullable<int> xArea { get; set; }
        public Nullable<int> xLength { get; set; }
        public Nullable<int> xWidth { get; set; }
        public Nullable<int> xGenCoolingSystem_ { get; set; }
        public Nullable<bool> xGenCoolingSystem_CkM { get; set; }
        public string xGenCoolingSystem_Remark { get; set; }
        public Nullable<int> xGenHeatingSystem_ { get; set; }
        public Nullable<bool> xGenHeatingSystem_CkM { get; set; }
        public string xGenHeatingSystem_Remark { get; set; }
        public Nullable<int> xBedroomsNumber { get; set; }
        public Nullable<bool> xBedroomsNumber_CkM { get; set; }
        public string xBedroomsNumber_Remark { get; set; }
        public Nullable<int> xBathroomNumber { get; set; }
        public Nullable<bool> xBathroomNumber_CkM { get; set; }
        public string xBathroomNumber_Remark { get; set; }
        public Nullable<int> xToiletNumber { get; set; }
        public Nullable<bool> xToiletNumber_CkM { get; set; }
        public string xToiletNumber_Remark { get; set; }
        public Nullable<int> xGenFlooring_ { get; set; }
        public Nullable<bool> xGenFlooring_CkM { get; set; }
        public string xGenFlooring_Remark { get; set; }
        public Nullable<int> xGenKitchenCupboards_ { get; set; }
        public Nullable<bool> xGenKitchenCupboards_CkM { get; set; }
        public string xGenKitchenCupboards_Remark { get; set; }
        public Nullable<bool> xBathtub { get; set; }
        public Nullable<bool> xBathtub_CkM { get; set; }
        public string xBathtub_Remark { get; set; }
        public Nullable<bool> xJacuzzi { get; set; }
        public Nullable<bool> xJacuzzi_Ckm { get; set; }
        public string xJacuzzi_Remark { get; set; }
        public Nullable<bool> xSauna { get; set; }
        public Nullable<bool> xSauna_Ckm { get; set; }
        public string xSauna_Remark { get; set; }
        public string xComment { get; set; }
    
        public virtual mRenovation mRenovation { get; set; }
    }
}
