//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mRenovationFloor
    {
        public mRenovationFloor()
        {
            this.mRenovationProjectAnswers = new HashSet<mRenovationProjectAnswer>();
        }
    
        public int x_ { get; set; }
        public Nullable<int> xRenovationProject_ { get; set; }
        public string xUnitNumber { get; set; }
        public Nullable<int> xGenUnitType_ { get; set; }
    
        public virtual mRenovationProject mRenovationProject { get; set; }
        public virtual ICollection<mRenovationProjectAnswer> mRenovationProjectAnswers { get; set; }
    }
}
