//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mRenovationProjectAnswer
    {
        public int x_ { get; set; }
        public Nullable<int> xRenovationFloor_ { get; set; }
        public Nullable<int> xQuestion_ { get; set; }
        public Nullable<int> xQuestionItem_ { get; set; }
        public string xQestionContext { get; set; }
        public Nullable<int> xGenStatus_ { get; set; }
        public string xComment { get; set; }
        public Nullable<int> xSupplier_ { get; set; }
        public string xDate { get; set; }
    
        public virtual mGenGroup mGenGroup { get; set; }
        public virtual mRenovationFloor mRenovationFloor { get; set; }
    }
}
