//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mRenovation
    {
        public mRenovation()
        {
            this.mRenovationUnits = new HashSet<mRenovationUnit>();
        }
    
        public int x_ { get; set; }
        public string xDate { get; set; }
        public Nullable<int> xCustomer_ { get; set; }
        public Nullable<int> xGenUsageType_ { get; set; }
        public Nullable<int> xBuildingStatus_ { get; set; }
        public Nullable<int> xArea { get; set; }
        public string xZone { get; set; }
        public string xAddress { get; set; }
        public Nullable<int> xGenPosition_ { get; set; }
        public Nullable<int> xlength { get; set; }
        public Nullable<int> xWidth { get; set; }
        public Nullable<int> xGenContractType_ { get; set; }
        public Nullable<bool> xLicenseRenovation { get; set; }
        public string xLicenseRenovationComment { get; set; }
        public Nullable<bool> xProductionLicense { get; set; }
        public string xProductionLicenseComment { get; set; }
        public Nullable<int> xFloorsNumber { get; set; }
        public Nullable<bool> xFloorsNumber_Ckm { get; set; }
        public string xFloorsNumber_Remark { get; set; }
        public Nullable<int> xBuildingUnitsNumberRequest { get; set; }
        public Nullable<bool> xBuildingUnitsNumberRequest_Ckm { get; set; }
        public string xBuildingUnitsNumberRequest_Remark { get; set; }
        public Nullable<int> xParkingNumber { get; set; }
        public Nullable<bool> xParkingNumber_CkM { get; set; }
        public string xParkingNumber_Remark { get; set; }
        public Nullable<int> xStorageNumber { get; set; }
        public Nullable<bool> xStorageNumber_CkM { get; set; }
        public string xStorageNumber_Remark { get; set; }
        public Nullable<bool> xRoofGarden { get; set; }
        public Nullable<bool> xRoofGarden_CkM { get; set; }
        public string xRoofGarden_Remark { get; set; }
        public Nullable<int> xWeightDestruction { get; set; }
        public Nullable<int> xGenTransportDestructionMetod_ { get; set; }
        public Nullable<int> xGenAccessDestructionMetod_ { get; set; }
        public Nullable<int> xNeighborUnitCount { get; set; }
        public Nullable<int> xNeighborsLivingNumber { get; set; }
        public Nullable<int> xRiskNeighborsComplaints { get; set; }
        public Nullable<int> xRiskMunicipalityPrevent { get; set; }
        public Nullable<int> xRiskDamageBuildingNeighbors { get; set; }
        public Nullable<int> xDestructionDurationDay { get; set; }
        public Nullable<int> xGenReasonsRenovation_ { get; set; }
        public Nullable<int> xSupplier_ { get; set; }
        public string xComment { get; set; }
    
        public virtual ICollection<mRenovationUnit> mRenovationUnits { get; set; }
    }
}
