//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mShift
    {
        public int x_ { get; set; }
        public string xShiftName { get; set; }
        public string xShiftSuperviser { get; set; }
        public string xShiftInspector { get; set; }
        public string xFernesSuperviser { get; set; }
        public string xSandOperator { get; set; }
    }
}
