//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mSMSLog
    {
        public int x_ { get; set; }
        public string xDate { get; set; }
        public string xTime { get; set; }
        public Nullable<int> xUser_ { get; set; }
        public string xContext { get; set; }
        public string xMobile { get; set; }
        public string xForm { get; set; }
        public string xResult { get; set; }
    }
}
