//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mStatementRefer
    {
        public mStatementRefer()
        {
            this.mStatementReferFollowUps = new HashSet<mStatementReferFollowUp>();
        }
    
        public int x_ { get; set; }
        public Nullable<int> xConsultant_ { get; set; }
        public string xFileNumber { get; set; }
        public string xFileDate { get; set; }
        public string xBuildingOwnerName { get; set; }
        public string xBuildingOwnerTel { get; set; }
        public string xBuildingAddress { get; set; }
        public string xFailureConcludeContract { get; set; }
        public string xFollowUpDate { get; set; }
        public string xFollowUpType { get; set; }
        public string xComment { get; set; }
        public Nullable<int> xGenFollowUpFinalResult_ { get; set; }
        public string xFollowUpFinalResult { get; set; }
        public string xSuggestedItems { get; set; }
        public string xSoldItems { get; set; }
        public Nullable<long> xContractCost { get; set; }
        public Nullable<long> xConsultantCommission { get; set; }
        public Nullable<bool> xReferFinanceConfirm { get; set; }
        public Nullable<int> xSupplierReferFinanceConfirm_ { get; set; }
        public string xFollowUpComment { get; set; }
        public Nullable<bool> xSendMessage { get; set; }
    
        public virtual ICollection<mStatementReferFollowUp> mStatementReferFollowUps { get; set; }
    }
}
