//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mStatu
    {
        public long x_ { get; set; }
        public Nullable<int> xUser_ { get; set; }
        public Nullable<bool> xStatus { get; set; }
        public Nullable<bool> xClose { get; set; }
        public string xMessage { get; set; }
        public Nullable<bool> xShowMessage { get; set; }
    }
}
