//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mStatementRentalIncome
    {
        public int x_ { get; set; }
        public string xContractDate { get; set; }
        public string xContractNumber { get; set; }
        public Nullable<int> xGenBuildingType_ { get; set; }
        public string xBuildingAddress { get; set; }
        public Nullable<long> xMortgage { get; set; }
        public Nullable<long> xRent { get; set; }
        public Nullable<long> xGuildCommission { get; set; }
        public string xContractConsultant { get; set; }
        public string xContractManager { get; set; }
        public string xLessorName { get; set; }
        public string xLessorAddress { get; set; }
        public string xLessorNationalCode { get; set; }
        public string xLessorTel { get; set; }
        public Nullable<long> xLessorEarnestCommission { get; set; }
        public Nullable<long> xLessorCommission { get; set; }
        public string xTenantName { get; set; }
        public string xTenantAddress { get; set; }
        public string xTenantNationalCode { get; set; }
        public string xTenantTel { get; set; }
        public Nullable<long> xTenantEarnestCommission { get; set; }
        public Nullable<long> xTenantCommission { get; set; }
        public string xHomeDeliveryDate { get; set; }
        public string xContractEndDate { get; set; }
        public Nullable<bool> xFinancialApprove { get; set; }
        public Nullable<int> xFinancialApprove_ { get; set; }
        public Nullable<int> xSupplier_ { get; set; }
        public string xComment { get; set; }
    }
}
