//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mStatementSaleIncome
    {
        public int x_ { get; set; }
        public string xContractDate { get; set; }
        public string xContractNumber { get; set; }
        public Nullable<int> xGenBuildingType_ { get; set; }
        public string xBuildingAddress { get; set; }
        public Nullable<long> xPrice { get; set; }
        public Nullable<long> xGuildCommission { get; set; }
        public string xContractConsultant { get; set; }
        public string xContractManager { get; set; }
        public string xSellerName { get; set; }
        public string xSellerAddress { get; set; }
        public string xSellerNationalCode { get; set; }
        public string xSellerTel { get; set; }
        public Nullable<long> xSellerEarnestCommission { get; set; }
        public Nullable<long> xSellerCommission { get; set; }
        public string xBuyerName { get; set; }
        public string xBuyerAddress { get; set; }
        public string xBuyerNationalCode { get; set; }
        public string xBuyerTel { get; set; }
        public Nullable<long> xBuyerEarnestCommission { get; set; }
        public Nullable<long> xBuyerCommission { get; set; }
        public Nullable<bool> xFinancialApprove { get; set; }
        public Nullable<int> xFinancialApprove_ { get; set; }
        public string xComment { get; set; }
        public string xHomeDeliveryDate { get; set; }
        public string xDocumentTransferDate { get; set; }
        public Nullable<int> xSupplier_ { get; set; }
    }
}
