//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mStoreDetial
    {
        public int x_ { get; set; }
        public string xGoodsCode { get; set; }
        public string xGoodsContext { get; set; }
        public Nullable<int> xGoods_ { get; set; }
        public string xUnits { get; set; }
        public string xBrand { get; set; }
        public string xSupplierCompany { get; set; }
        public Nullable<double> xAmount { get; set; }
        public Nullable<int> xPrice { get; set; }
        public Nullable<int> xDiscount { get; set; }
        public Nullable<int> xStore_ { get; set; }
    
        public virtual mGood mGood { get; set; }
        public virtual mStore mStore { get; set; }
    }
}
