//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mUser
    {
        public mUser()
        {
            this.mAuthentications = new HashSet<mAuthentication>();
        }
    
        public int x_ { get; set; }
        public string xUserName { get; set; }
        public string xPasswod { get; set; }
        public string xName { get; set; }
        public string xFamily { get; set; }
        public string xTel { get; set; }
        public string xEmail { get; set; }
        public Nullable<int> xGroup_ { get; set; }
        public bool xActive { get; set; }
        public Nullable<int> xPerInfo_ { get; set; }
    
        public virtual ICollection<mAuthentication> mAuthentications { get; set; }
        public virtual mGroup mGroup { get; set; }
        public virtual mPersonInfo mPersonInfo { get; set; }
    }
}
