//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwModelData.StatementRefer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mUserevent
    {
        public int x_ { get; set; }
        public string xEventTime { get; set; }
        public string xEventType { get; set; }
        public string xEventCode { get; set; }
        public string xMessage { get; set; }
        public string xMachinename { get; set; }
        public string xDetails { get; set; }
        public string xIp { get; set; }
        public string xUserId { get; set; }
    }
}
